### ISSUE TITLE
File Upload Failed

### ISSUE THREAD

**Issue by bhi5hmaraj** [AlgoWiki/AlgoWiki#5]
I have a PDF of a [book](https://books.google.co.in/books/about/Data_Structure_Practice.html?id=E22mCwAAQBAJ&redir_esc=y)  its around 12MB . It fails to upload saying file limit reached . You can find the link to the PDF [here](http://www3.cs.stonybrook.edu/~rezaul/Spring-2015/CSE548/Yonghui-Wu/Yonghui-Wu-books.pdf)

**Comment by SuprDewd** [comment]
I see you already [found a solution](https://wiki.algo.is/_diff/Competitive%20programming%20resources?to=682cad739bc1a7f19deb12ca39bba6275d781ad0). And yes, I would prefer linking to that PDF than uploading it.

However, do you know if the book has an official homepage or a page that would make more sense to link to? Somewhere you can possibly see the table of contents, and a link to where you can buy/access the book?

**Comment by bhi5hmaraj** [comment]
I think [this](http://www.crcnetbase.com/isbn/978-1-4822-1539-7) is what were looking for.

**Comment by SuprDewd** [comment]
To address the "File Upload Failed", this file size limit is deliberately set to a relatively small size (100KiB currently) to keep the wiki from being bloated with large files. I think it makes more sense, and especially in the case of the PDF you posted, to link to these online resources instead (the downside being that these links may eventually die, but I have [plans](http://codeforces.com/blog/entry/50528) for fixing that).

I think an exception to this would be image files, where it might make more sense to store them in the wiki. If you (or someone else) can't upload files to the wiki because of size constraints, but still think they belong in the wiki, feel free to submit a pull request directly here on Github, where there is a much larger file size limit. If I later see a reason to, I might also consider increasing the limit on the wiki.

**Comment by SuprDewd** [comment]
> I think this is what were looking for.

Great! I clicked on "About this Book" in your link, and found [this](https://www.crcpress.com/Data-Structure-Practice-for-Collegiate-Programming-Contests-and-Education/Wu-Wang/p/book/9781482215397) page, which I think might be an even better fit. Feel free to update the wiki page to point to this page instead. I can also do it, if you prefer.

Thanks for your contributions so far!
